theme: jekyll-theme-minimal
title: Welcome to Arjun Dhatt's homepage
description: This is a website where I will upload a digital CV, my experience with various statistics courses & interesting R resources. 
